name: PR Compare
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['main']
    paths:
      - models/**
      - seeds/**
      - tests/**

jobs:
  piperider-compare:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

    - name: PipeRider Compare
      uses: InfuseAI/piperider-compare-action@v1.2.0-beta.1
      with:
        cloud_api_token: ${{ secrets.PIPERIDER_CLOUD_TOKEN_ID }}
        cloud_project: ${{ secrets.PIPERIDER_API_PROJECT }}
        upload: true
        share: true
        modified: true
        piperider_version: v0.29.3-rc.1
